source 'https://github.com/CocoaPods/Specs.git'
xcodeproj './SoundSieve.xcodeproj'
use_frameworks!
pod 'XLForm', '3.0.0'
pod 'OAuthSwift'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'DrawerController'
pod 'HTPressableButton'
pod 'UCZProgressView'
pod 'MDCSwipeToChoose'
pod 'Fabric'
pod 'Crashlytics'
